#!/bin/bash

#
# This script will set up the environment for ansible to run a playbook,
# configuring the python environment, downloading ansible collections and
# displaying relevant runtime information.
#
# Requirements for the script to run:
# + The playbook directory must be writeable - The python env and ansible cache
#   are stored there.
# + The playbook directory must have an ansible.cfg file
# + The playbook directory must have a requirements.txt and requirements.yml file
#   specifying the python and ansible requirements, respectively.
#

# Global settings
set -o pipefail

# Every command in the script needs to complete successfully
set -e

########
# Determine playbook and working directory
PLAYBOOK=$(readlink -f "$1")
shift
WORKDIR=$(dirname "${PLAYBOOK}")
ORIGDIR=$(pwd)

# Make sure the playbook exists before we start doing any work
if [ ! -f "${PLAYBOOK}" ] ; then
  echo "Playbook does not exist: ${PLAYBOOK}"
  exit 1
fi

# Change to workdir temporarily - error handling by 'set -e'
cd "${WORKDIR}"

# Change HOME to WORKDIR
HOME="${WORKDIR}"

echo "Working directory: ${WORKDIR}"
echo "New HOME directory: ${HOME}"

########
# Set up environment

# Set up venv for ansible
echo ""
echo "Configuring python virtualenv"
echo "----------------"
python3 -m venv env
# shellcheck disable=SC1091
source ./env/bin/activate

echo ""
echo "Configuring pip"
echo "----------------"
python3 -m pip install --upgrade pip
python3 -m pip install -r requirements.txt
python3 -m pip list

# Resolve ansible requirements
echo ""
echo "Installing ansible collections"
echo "----------------"
ansible-galaxy collection install -r requirements.yml
ansible-galaxy collection list

echo ""
echo "Installing ansible roles"
echo "----------------"
ansible-galaxy role install -r requirements.yml
ansible-galaxy role list

# Ansible config file
echo ""
echo "Setting ansible.cfg location"
echo "----------------"
export ANSIBLE_CONFIG="${WORKDIR}/ansible.cfg"
if [ ! -f "${ANSIBLE_CONFIG}" ] ; then
  echo "Missing ansible.cfg file: ${ANSIBLE_CONFIG}"
  exit 1
fi
echo "ANSIBLE_CONFIG: ${ANSIBLE_CONFIG}"
echo ""

########
# Start ansible playbook

# Display run information
echo ""
echo "Ansible runtime information"
echo "----------------"
echo "Ansible Install Location: $(which ansible-playbook)"
echo ""
echo "Ansible-Playbook Version: "
ansible-playbook --version
echo ""

# Move back to origin directory before starting the playbook
cd "${ORIGDIR}"

echo "Starting ansible playbook"
echo "----------------"
exec ansible-playbook "${PLAYBOOK}" "$@"

exit 1
