#!/bin/bash

# Global settings
SCRIPT=`readlink -f $0`
DIR=`dirname "${SCRIPT}"`
set -o pipefail

# Starting directory
STARTDIR="$1"
shift
cd "$STARTDIR" || exit 1

# Determine environment
ENV="$1"
shift

# Set up venv for ansible
python3 -m venv env
source ./env/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install -r requirements-python.txt

# Resolve ansible requirements
ansible-galaxy collection install -r requirements-ansible.yml

# Ansible config file
export ANSIBLE_CONFIG="./ansible.cfg"

# Display run information
echo "Environment: $ENV"
echo "Ansible Install Location: "
which ansible-playbook

echo "Ansible-Playbook Version: "
ansible-playbook --version

exec ansible-playbook ./main.yml -i "./inventory/shared" -i "./inventory/$ENV" "$@"

exit 1
