#!/bin/bash

# Global settings
set -o pipefail
SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "${SCRIPT_PATH}")

. "${SCRIPT_DIR}/library"

# Support functions

function usage() {
  cat <<_EOF_
commands:
  next_env
  env_promote
  ansible-playbook
_EOF_
}

COMMAND="$1"
shift

case "$COMMAND" in
  next_env)
    if ! next_env "$@" ; then
      echo "Failed to perform next_env"
      exit 1
    fi
    ;;
  env_promote)
    if ! env_promote "$@" ; then
      echo "Failed to perform env_promote"
      exit 1
    fi
    ;;
  ansible-playbook)
    if ! ansible_playbook "$@" ; then
      echo "Failed to run ansible-playbook"
      exit 1
    fi
    ;;
  ""|"help")
    usage
    exit 0
    ;;
  *)
    echo "Unknown command: $COMMAND"
    exit 1
    ;;
esac

exit 0
